name: AdventureLog
main: com.github.jikoo.AdventureLogPlugin
version: ${project.version}
author: Jikoo
description: Exploration-based waypoints!
api-version: "1.16"

permissions:
  adventurelog.*:
    default: op
    children:
      adventurelog.givelog: true
      adventurelog.givelog.other: true
      adventurelog.unlockwaypoint: true
      adventurelog.lockwaypoint: true
      adventurelog.managewaypoints: true
      adventurelog.personal.unlimited: true

commands:
  givelog:
    description: Give a user an Adventure Log.
    usage: /givelog [player]
    permission: adventurelog.givelog
  managewaypoints:
    aliases: [editwaypoints]
    description: Manage Adventure Log waypoints
    usage: /<command>
    permission: adventurelog.managewaypoints
  unlocklogwaypoint:
    aliases: [unlockwaypoint]
    description: Unlock a new Adventure Log waypoint
    usage: /unlocklogwaypoint <player> <name>
    permission: adventurelog.unlockwaypoint
  locklogwaypoint:
    aliases: [lockwaypoint]
    description: Lock an Adventure Log waypoint
    usage: /locklogwaypoint <player> <name>
    permission: adventurelog.lockwaypoint
