name: AdventureLog
main: com.github.jikoo.AdventureLogPlugin
version: ${project.version}
author: Jikoo
description: Exploration-based waypoints!
api-version: "1.14"

permissions:
  adventurelog.*:
    default: op
    children:
      adventurelog.givelog: true
      adventurelog.givelog.other: true
      adventurelog.addwaypoint: true
      adventurelog.removewaypoint: true
      adventurelog.unlockwaypoint: true
      adventurelog.lockwaypoint: true
      adventurelog.adddefaultwaypoint: true
      adventurelog.removedefaultwaypoint: true


commands:
  givelog:
    description: Give a user an Adventure Log.
    usage: /givelog [player]
    permission: adventurelog.givelog
  addlogwaypoint:
    aliases: [addwaypoint, waypoint]
    description: Add a new Adventure Log waypoint
    usage: /addlogwaypoint <name> [priority] [default]
    permission: adventurelog.addwaypoint
  removelogwaypoint:
    aliases: [removewaypoint, dellogwaypoint, delwaypoint]
    description: Remove an Adventure Log waypoint
    usage: /removelogwaypoint <name>
    permission: adventurelog.removewaypoint
  unlocklogwaypoint:
    aliases: [unlockwaypoint]
    description: Unlock a new Adventure Log waypoint
    usage: /unlocklogwaypoint <player> <name>
    permission: adventurelog.unlockwaypoint
  locklogwaypoint:
    aliases: [lockwaypoint]
    description: Lock an Adventure Log waypoint
    usage: /locklogwaypoint <player> <name>
    permission: adventurelog.lockwaypoint
  adddefaultlogwaypoint:
    aliases: [adddefaultwaypoint, defaultwaypoint]
    description: Add an Adventure Log waypoint to the default list
    usage: /adddefaultlogwaypoint <name>
    permission: adventurelog.adddefaultwaypoint
  removedefaultlogwaypoint:
    aliases: [removedefaultwaypoint, deldefaultlogwaypoint, deldefaultwaypoint]
    description: Remove an Adventure Log waypoint from the default list
    usage: /removedefaultlogwaypoint <name>
    permission: adventurelog.removedefaultwaypoint